apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: l7mp-ingress
  labels:
    apps: l7mp-ingress
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  template:
    metadata:
      labels:
        app: l7mp-ingress
    spec:
      volumes:
        - name: l7mp-ingress-config
          configMap:
            name: l7mp-ingress
      containers:
      - name: l7mp
        image: "{{ .values.l7mp_proxy_image.repository }}{{ .values.l7mp_proxy_image.name }}:{{ .values.l7mp_proxy_image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .values.l7mp_proxy_image.pullPolicy }}
        command: [ "node" ]
        args: [ "l7mp-proxy.js", "-c", "config/l7mp-ingress.yaml", "-s", "-l", "{{ .values.l7mp_proxy_image.logLevel }}" ]
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 1234
        volumeMounts:
          - name: l7mp-ingress-config
            mountPath: /app/config
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
